export interface CandleSvgProps {
  bodyTop: number;
  bodyBottom: number;
  wickTop: number;
  wickBottom: number;
  bullish: boolean;
}

export interface CandlestickPattern {
  name: string;
  sentiment: string;
  psychology: string;
  entry: string;
  stopLoss: string;
  confirmation: string;
  candles: CandleSvgProps[];
  type: 'reversal' | 'continuation';
  indianNote?: string;
}

export interface PatternCategory {
  title: string;
  patterns: CandlestickPattern[];
}

export const categories: PatternCategory[] = [
  {
    title: 'Single Candle Patterns',
    patterns: [
      {
        name: 'Hammer',
        sentiment: 'Strong Bullish',
        psychology: 'Sellers pushed price sharply lower, but buyers stepped in aggressively and drove it back near the open. Buyer strength emerged at the bottom.',
        entry: 'Enter long when the next candle closes above the Hammer high.',
        stopLoss: 'Place stop-loss below the Hammer lower wick.',
        confirmation: 'The next candle must close bullish and above the Hammer body to validate the reversal.',
        candles: [{ bodyTop: 35, bodyBottom: 45, wickTop: 30, wickBottom: 95, bullish: true }],
        type: 'reversal',
      },
      {
        name: 'Inverted Hammer',
        sentiment: 'Weak Bullish',
        psychology: 'Buyers attempted to push higher but sellers fought back. The attempt itself signals a potential momentum shift after a downtrend.',
        entry: 'Enter above the Inverted Hammer high on confirmation.',
        stopLoss: 'Stop-loss below the low of the candle.',
        confirmation: 'The next candle must open and close above the Inverted Hammer body — a gap up adds strength.',
        candles: [{ bodyTop: 75, bodyBottom: 85, wickTop: 25, wickBottom: 90, bullish: true }],
        type: 'reversal',
      },
      {
        name: 'Shooting Star',
        sentiment: 'Strong Bearish',
        psychology: 'Buyers pushed price to new highs but sellers took control and drove it back near the open. Upper wick shows rejection at resistance.',
        entry: 'Enter short when the next candle closes below the Shooting Star low.',
        stopLoss: 'Stop-loss above the upper wick.',
        confirmation: 'The next candle must close bearish and below the Shooting Star body to confirm the reversal.',
        candles: [{ bodyTop: 75, bodyBottom: 85, wickTop: 20, wickBottom: 90, bullish: false }],
        type: 'reversal',
      },
      {
        name: 'Hanging Man',
        sentiment: 'Weak Bearish',
        psychology: 'Looks like a Hammer but at the top of an uptrend. Sellers are starting to emerge — the long lower shadow warns that buying pressure is fading.',
        entry: 'Enter short below the Hanging Man low on confirmation.',
        stopLoss: 'Stop-loss above the Hanging Man high.',
        confirmation: 'The next candle must close bearish, ideally below the Hanging Man open, to validate the signal.',
        candles: [{ bodyTop: 30, bodyBottom: 40, wickTop: 25, wickBottom: 90, bullish: false }],
        type: 'reversal',
      },
      {
        name: 'Doji',
        sentiment: 'Neutral',
        psychology: 'Open and close are virtually equal — neither buyers nor sellers won. After a strong trend, it warns momentum is fading and a reversal may be near.',
        entry: 'Wait for the next candle to set direction, then enter above/below the Doji range.',
        stopLoss: 'Stop-loss on the opposite side of the Doji wick.',
        confirmation: 'The next candle must break decisively beyond the Doji range in either direction.',
        candles: [{ bodyTop: 58, bodyBottom: 60, wickTop: 30, wickBottom: 90, bullish: true }],
        type: 'reversal',
      },
      {
        name: 'Marubozu',
        sentiment: 'Strong Bullish',
        psychology: 'A full-bodied candle with no wicks — buyers (or sellers) dominated the entire session without any opposition. Pure conviction.',
        entry: 'For bullish Marubozu: enter long at close or on a small pullback. For bearish: enter short.',
        stopLoss: 'Stop-loss at the midpoint of the Marubozu body.',
        confirmation: 'The next candle should continue in the same direction. A reversal candle immediately after weakens the signal.',
        candles: [{ bodyTop: 25, bodyBottom: 90, wickTop: 25, wickBottom: 90, bullish: true }],
        type: 'continuation',
      },
      // NEW Single patterns
      {
        name: 'Spinning Top',
        sentiment: 'Neutral',
        psychology: 'Small body with long upper and lower wicks — both buyers and sellers made strong moves but neither side won. Pure indecision that often precedes a breakout.',
        entry: 'Wait for the next candle to break the Spinning Top range, then enter in that direction.',
        stopLoss: 'Stop-loss on the opposite wick of the Spinning Top.',
        confirmation: 'A decisive close above or below the Spinning Top range with volume confirms the next move.',
        candles: [{ bodyTop: 52, bodyBottom: 60, wickTop: 22, wickBottom: 90, bullish: true }],
        type: 'reversal',
      },
      {
        name: 'Dragonfly Doji',
        sentiment: 'Strong Bullish',
        psychology: 'Open, close, and high are all near the same level with a long lower shadow. Sellers pushed hard but buyers absorbed every bit of selling and reclaimed the open — powerful bullish rejection.',
        entry: 'Enter long above the Dragonfly Doji high on the next candle.',
        stopLoss: 'Stop-loss below the lower wick.',
        confirmation: 'The next candle must close bullish with increased volume to confirm buyer control.',
        candles: [{ bodyTop: 28, bodyBottom: 30, wickTop: 26, wickBottom: 92, bullish: true }],
        type: 'reversal',
      },
      {
        name: 'Gravestone Doji',
        sentiment: 'Strong Bearish',
        psychology: 'Open, close, and low are near the same level with a long upper shadow. Buyers pushed aggressively higher but sellers slammed it back to the open — a bearish rejection at the top.',
        entry: 'Enter short below the Gravestone Doji low on confirmation.',
        stopLoss: 'Stop-loss above the upper wick.',
        confirmation: 'The next candle must close bearish and below the Gravestone body to validate the reversal.',
        candles: [{ bodyTop: 82, bodyBottom: 84, wickTop: 20, wickBottom: 88, bullish: false }],
        type: 'reversal',
      },
      {
        name: 'Long-Legged Doji',
        sentiment: 'Neutral',
        psychology: 'Extremely long wicks on both sides with a tiny body at the center. Represents maximum indecision — both sides fought violently but ended in a draw. A major turning point signal.',
        entry: 'Wait for a decisive break of either wick, then enter in that direction.',
        stopLoss: 'Stop-loss at the opposite wick end.',
        confirmation: 'The next candle must close convincingly beyond the Doji range. Higher volume adds reliability.',
        candles: [{ bodyTop: 54, bodyBottom: 58, wickTop: 15, wickBottom: 95, bullish: true }],
        type: 'reversal',
      },
    ],
  },
  {
    title: 'Double Candle Patterns',
    patterns: [
      {
        name: 'Bullish Engulfing',
        sentiment: 'Strong Bullish',
        psychology: 'A small bearish candle is completely swallowed by a larger bullish candle. Buyers overwhelmed sellers — momentum has shifted.',
        entry: 'Enter long at the close of the engulfing candle or on a break above its high.',
        stopLoss: 'Stop-loss below the low of the engulfing candle.',
        confirmation: 'The next candle must close bullish, confirming buyer control.',
        candles: [
          { bodyTop: 55, bodyBottom: 70, wickTop: 50, wickBottom: 75, bullish: false },
          { bodyTop: 40, bodyBottom: 80, wickTop: 35, wickBottom: 85, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Bearish Engulfing',
        sentiment: 'Strong Bearish',
        psychology: 'A small bullish candle is completely engulfed by a larger bearish candle. Sellers overwhelmed buyers at the top of an uptrend.',
        entry: 'Enter short at the close of the engulfing candle.',
        stopLoss: 'Stop-loss above the high of the engulfing candle.',
        confirmation: 'The next candle must close bearish to confirm seller dominance.',
        candles: [
          { bodyTop: 50, bodyBottom: 65, wickTop: 45, wickBottom: 70, bullish: true },
          { bodyTop: 35, bodyBottom: 75, wickTop: 30, wickBottom: 80, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Bullish Harami',
        sentiment: 'Weak Bullish',
        psychology: 'A small bullish candle forms inside the body of a larger bearish candle. Selling pressure is weakening — buyers are starting to test control.',
        entry: 'Enter long above the high of the second (small) candle.',
        stopLoss: 'Stop-loss below the low of the first (large) candle.',
        confirmation: 'The next candle must break above the Harami high to validate the reversal.',
        candles: [
          { bodyTop: 30, bodyBottom: 80, wickTop: 25, wickBottom: 85, bullish: false },
          { bodyTop: 48, bodyBottom: 62, wickTop: 45, wickBottom: 65, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Bearish Harami',
        sentiment: 'Weak Bearish',
        psychology: 'A small bearish candle forms inside the body of a larger bullish candle. Buying momentum is fading — sellers are gaining a foothold.',
        entry: 'Enter short below the low of the second (small) candle.',
        stopLoss: 'Stop-loss above the high of the first (large) candle.',
        confirmation: 'The next candle must break below the Harami low to confirm the reversal.',
        candles: [
          { bodyTop: 30, bodyBottom: 80, wickTop: 25, wickBottom: 85, bullish: true },
          { bodyTop: 45, bodyBottom: 60, wickTop: 42, wickBottom: 63, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Piercing Line',
        sentiment: 'Strong Bullish',
        psychology: 'After a bearish candle, the next candle opens below the low but closes above the midpoint of the first. Buyers fought back with conviction at the bottom.',
        entry: 'Enter long at the close of the bullish candle.',
        stopLoss: 'Stop-loss below the low of the pattern.',
        confirmation: 'The next candle must close above the bullish candle close to confirm buyer strength.',
        candles: [
          { bodyTop: 35, bodyBottom: 70, wickTop: 30, wickBottom: 75, bullish: false },
          { bodyTop: 30, bodyBottom: 60, wickTop: 25, wickBottom: 78, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Dark Cloud Cover',
        sentiment: 'Strong Bearish',
        psychology: 'After a bullish candle, the next opens above the high but closes below the midpoint. Sellers aggressively rejected higher prices.',
        entry: 'Enter short at the close of the bearish candle.',
        stopLoss: 'Stop-loss above the pattern high.',
        confirmation: 'The next candle must close bearish to validate the reversal signal.',
        candles: [
          { bodyTop: 40, bodyBottom: 75, wickTop: 35, wickBottom: 80, bullish: true },
          { bodyTop: 30, bodyBottom: 62, wickTop: 25, wickBottom: 65, bullish: false },
        ],
        type: 'reversal',
      },
      // NEW Double patterns
      {
        name: 'Tweezer Bottoms',
        sentiment: 'Strong Bullish',
        psychology: 'Two consecutive candles share the same low — the market tested a level twice and rejected it both times. Double rejection = strong support.',
        entry: 'Enter long above the high of the second candle.',
        stopLoss: 'Stop-loss below the shared low.',
        confirmation: 'The next candle must close bullish above both candle bodies to confirm the double-bottom rejection.',
        candles: [
          { bodyTop: 45, bodyBottom: 75, wickTop: 40, wickBottom: 88, bullish: false },
          { bodyTop: 40, bodyBottom: 70, wickTop: 35, wickBottom: 88, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Tweezer Tops',
        sentiment: 'Strong Bearish',
        psychology: 'Two consecutive candles share the same high — the market attempted to break resistance twice and failed. Double rejection = strong resistance.',
        entry: 'Enter short below the low of the second candle.',
        stopLoss: 'Stop-loss above the shared high.',
        confirmation: 'The next candle must close bearish below both candle bodies to confirm the double-top rejection.',
        candles: [
          { bodyTop: 35, bodyBottom: 65, wickTop: 22, wickBottom: 70, bullish: true },
          { bodyTop: 40, bodyBottom: 68, wickTop: 22, wickBottom: 72, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Bullish Harami Cross',
        sentiment: 'Strong Bullish',
        psychology: 'A Doji forms inside the body of a large bearish candle — selling momentum has completely stalled. The Doji shows perfect equilibrium after panic selling.',
        entry: 'Enter long above the Doji high on the next candle.',
        stopLoss: 'Stop-loss below the low of the large bearish candle.',
        confirmation: 'The next candle must close bullish above the Doji. Volume increase strengthens the signal.',
        candles: [
          { bodyTop: 30, bodyBottom: 80, wickTop: 25, wickBottom: 85, bullish: false },
          { bodyTop: 54, bodyBottom: 56, wickTop: 45, wickBottom: 65, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Bearish Harami Cross',
        sentiment: 'Strong Bearish',
        psychology: 'A Doji forms inside the body of a large bullish candle — buying momentum has completely exhausted. The Doji signals indecision at the peak of a rally.',
        entry: 'Enter short below the Doji low on the next candle.',
        stopLoss: 'Stop-loss above the high of the large bullish candle.',
        confirmation: 'The next candle must close bearish below the Doji. Declining volume on the bullish candle adds conviction.',
        candles: [
          { bodyTop: 30, bodyBottom: 80, wickTop: 25, wickBottom: 85, bullish: true },
          { bodyTop: 54, bodyBottom: 56, wickTop: 42, wickBottom: 65, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Bullish Kicker',
        sentiment: 'Strong Bullish',
        psychology: 'A bearish candle is followed by a bullish candle that gaps up above the prior open — a violent sentiment reversal. Overnight news or institutional buying triggered an immediate shift.',
        entry: 'Enter long at the open of the bullish candle or on a pullback to its open.',
        stopLoss: 'Stop-loss below the low of the bullish candle.',
        confirmation: 'No additional confirmation needed — the Kicker is one of the most reliable patterns. Volume should be significantly above average.',
        candles: [
          { bodyTop: 45, bodyBottom: 80, wickTop: 40, wickBottom: 85, bullish: false },
          { bodyTop: 20, bodyBottom: 42, wickTop: 15, wickBottom: 44, bullish: true },
        ],
        type: 'reversal',
        indianNote: '🇮🇳 High-impact but rare in Nifty/Sensex — typically occurs after major overnight events, RBI policy surprises, or global sentiment shifts. When it appears, it carries exceptional reliability.',
      },
      {
        name: 'Bearish Kicker',
        sentiment: 'Strong Bearish',
        psychology: 'A bullish candle is followed by a bearish candle that gaps down below the prior open — a violent sentiment reversal. Overnight shock or institutional selling triggered panic.',
        entry: 'Enter short at the open of the bearish candle or on a retracement to its open.',
        stopLoss: 'Stop-loss above the high of the bearish candle.',
        confirmation: 'No additional confirmation needed — the Kicker is one of the most reliable patterns. Volume should be significantly above average.',
        candles: [
          { bodyTop: 30, bodyBottom: 65, wickTop: 25, wickBottom: 70, bullish: true },
          { bodyTop: 68, bodyBottom: 92, wickTop: 66, wickBottom: 95, bullish: false },
        ],
        type: 'reversal',
        indianNote: '🇮🇳 High-impact but rare in Nifty/Sensex — typically seen after sudden policy changes, geopolitical events, or unexpected earnings shocks in heavyweight stocks like Reliance or HDFC Bank.',
      },
    ],
  },
  {
    title: 'Triple / Multi-Candle Patterns',
    patterns: [
      {
        name: 'Morning Star',
        sentiment: 'Strong Bullish',
        psychology: 'Bearish candle → small indecision candle → strong bullish candle. Marks the exact transition from seller control to buyer control at a bottom.',
        entry: 'Enter long at the close of the third candle.',
        stopLoss: 'Stop-loss below the low of the middle candle.',
        confirmation: 'The third candle must close above the midpoint of the first candle. Volume on the third candle should be higher.',
        candles: [
          { bodyTop: 35, bodyBottom: 70, wickTop: 30, wickBottom: 75, bullish: false },
          { bodyTop: 73, bodyBottom: 78, wickTop: 68, wickBottom: 85, bullish: false },
          { bodyTop: 30, bodyBottom: 65, wickTop: 25, wickBottom: 70, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Evening Star',
        sentiment: 'Strong Bearish',
        psychology: 'Strong bullish candle → small indecision candle → strong bearish candle. Signals the end of buying pressure at a market top.',
        entry: 'Enter short at the close of the third candle.',
        stopLoss: 'Stop-loss above the high of the middle candle.',
        confirmation: 'The third candle must close below the midpoint of the first candle. Increasing volume confirms the reversal.',
        candles: [
          { bodyTop: 40, bodyBottom: 75, wickTop: 35, wickBottom: 80, bullish: true },
          { bodyTop: 30, bodyBottom: 35, wickTop: 25, wickBottom: 40, bullish: true },
          { bodyTop: 38, bodyBottom: 75, wickTop: 33, wickBottom: 80, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Three White Soldiers',
        sentiment: 'Strong Bullish',
        psychology: 'Three consecutive long bullish candles, each opening within the prior body and closing higher. Sustained, aggressive buying — a powerful reversal signal.',
        entry: 'Enter long at the close of the third candle or on a pullback.',
        stopLoss: 'Stop-loss below the first candle low.',
        confirmation: 'Each candle should close near its high with minimal upper wick. The fourth candle should not be a large bearish reversal.',
        candles: [
          { bodyTop: 65, bodyBottom: 85, wickTop: 62, wickBottom: 88, bullish: true },
          { bodyTop: 45, bodyBottom: 68, wickTop: 42, wickBottom: 70, bullish: true },
          { bodyTop: 25, bodyBottom: 48, wickTop: 22, wickBottom: 50, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Three Black Crows',
        sentiment: 'Strong Bearish',
        psychology: 'Three consecutive long bearish candles, each opening within the prior body and closing lower. Relentless selling — a reliable reversal from an uptrend.',
        entry: 'Enter short at the close of the third candle.',
        stopLoss: 'Stop-loss above the first candle high.',
        confirmation: 'Each candle should close near its low with minimal lower wick. The fourth candle should not reclaim the third candle body.',
        candles: [
          { bodyTop: 25, bodyBottom: 48, wickTop: 22, wickBottom: 50, bullish: false },
          { bodyTop: 45, bodyBottom: 68, wickTop: 42, wickBottom: 70, bullish: false },
          { bodyTop: 65, bodyBottom: 85, wickTop: 62, wickBottom: 88, bullish: false },
        ],
        type: 'reversal',
      },
      // NEW Triple/Multi patterns
      {
        name: 'Three Inside Up',
        sentiment: 'Strong Bullish',
        psychology: 'A Bullish Harami followed by a third candle that closes above the first candle high — confirms the reversal with a breakout. The three candles narrate: selling → hesitation → buyer takeover.',
        entry: 'Enter long at the close of the third candle.',
        stopLoss: 'Stop-loss below the low of the first candle.',
        confirmation: 'The third candle must close above the high of the first bearish candle. Rising volume on the third candle is ideal.',
        candles: [
          { bodyTop: 35, bodyBottom: 75, wickTop: 30, wickBottom: 80, bullish: false },
          { bodyTop: 48, bodyBottom: 62, wickTop: 45, wickBottom: 65, bullish: true },
          { bodyTop: 25, bodyBottom: 50, wickTop: 22, wickBottom: 52, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Three Inside Down',
        sentiment: 'Strong Bearish',
        psychology: 'A Bearish Harami followed by a third candle that closes below the first candle low — confirms the reversal with a breakdown. The narrative: buying → hesitation → seller takeover.',
        entry: 'Enter short at the close of the third candle.',
        stopLoss: 'Stop-loss above the high of the first candle.',
        confirmation: 'The third candle must close below the low of the first bullish candle. Increasing volume adds conviction.',
        candles: [
          { bodyTop: 35, bodyBottom: 75, wickTop: 30, wickBottom: 80, bullish: true },
          { bodyTop: 48, bodyBottom: 62, wickTop: 45, wickBottom: 65, bullish: false },
          { bodyTop: 60, bodyBottom: 85, wickTop: 58, wickBottom: 90, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Three Outside Up',
        sentiment: 'Strong Bullish',
        psychology: 'A Bullish Engulfing followed by a third candle that closes even higher — double confirmation of buyer dominance. The engulfing starts the reversal, the third candle seals it.',
        entry: 'Enter long at the close of the third candle.',
        stopLoss: 'Stop-loss below the low of the engulfing candle.',
        confirmation: 'The third candle must close above the engulfing candle high with sustained volume.',
        candles: [
          { bodyTop: 55, bodyBottom: 68, wickTop: 52, wickBottom: 72, bullish: false },
          { bodyTop: 38, bodyBottom: 75, wickTop: 35, wickBottom: 78, bullish: true },
          { bodyTop: 25, bodyBottom: 40, wickTop: 22, wickBottom: 42, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Three Outside Down',
        sentiment: 'Strong Bearish',
        psychology: 'A Bearish Engulfing followed by a third candle that closes even lower — double confirmation of seller dominance. The engulfing triggers panic, the third candle accelerates it.',
        entry: 'Enter short at the close of the third candle.',
        stopLoss: 'Stop-loss above the high of the engulfing candle.',
        confirmation: 'The third candle must close below the engulfing candle low with increasing volume.',
        candles: [
          { bodyTop: 42, bodyBottom: 55, wickTop: 38, wickBottom: 58, bullish: true },
          { bodyTop: 35, bodyBottom: 72, wickTop: 32, wickBottom: 75, bullish: false },
          { bodyTop: 68, bodyBottom: 88, wickTop: 65, wickBottom: 92, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Abandoned Baby (Bullish)',
        sentiment: 'Strong Bullish',
        psychology: 'Bearish candle → gap-down Doji → gap-up bullish candle. The Doji is completely isolated by gaps on both sides — selling exhaustion followed by an explosive reversal. Extremely rare and powerful.',
        entry: 'Enter long at the close of the third candle.',
        stopLoss: 'Stop-loss below the Doji low.',
        confirmation: 'Both gaps must be present. The third candle should close above the midpoint of the first candle with strong volume.',
        candles: [
          { bodyTop: 30, bodyBottom: 58, wickTop: 26, wickBottom: 62, bullish: false },
          { bodyTop: 68, bodyBottom: 70, wickTop: 64, wickBottom: 76, bullish: true },
          { bodyTop: 28, bodyBottom: 58, wickTop: 24, wickBottom: 60, bullish: true },
        ],
        type: 'reversal',
        indianNote: '🇮🇳 Extremely rare in Nifty/Sensex due to continuous trading sessions and tight gaps. When it does appear (usually around F&O expiry or post-holiday gaps), it carries very high conviction.',
      },
      {
        name: 'Abandoned Baby (Bearish)',
        sentiment: 'Strong Bearish',
        psychology: 'Bullish candle → gap-up Doji → gap-down bearish candle. The Doji is isolated by gaps — buying exhaustion followed by violent selling. Extremely rare and powerful.',
        entry: 'Enter short at the close of the third candle.',
        stopLoss: 'Stop-loss above the Doji high.',
        confirmation: 'Both gaps must be present. The third candle should close below the midpoint of the first candle with strong volume.',
        candles: [
          { bodyTop: 50, bodyBottom: 78, wickTop: 46, wickBottom: 82, bullish: true },
          { bodyTop: 38, bodyBottom: 40, wickTop: 32, wickBottom: 44, bullish: false },
          { bodyTop: 50, bodyBottom: 78, wickTop: 48, wickBottom: 82, bullish: false },
        ],
        type: 'reversal',
        indianNote: '🇮🇳 Extremely rare in Nifty/Sensex — most commonly spotted around budget sessions, RBI policy announcements, or major global sell-offs. Treat as a high-conviction signal when it forms.',
      },
      {
        name: 'Morning Doji Star',
        sentiment: 'Strong Bullish',
        psychology: 'Like a Morning Star but the middle candle is a Doji — complete indecision at the bottom followed by a powerful bullish reversal. The Doji makes the equilibrium point more precise.',
        entry: 'Enter long at the close of the third candle.',
        stopLoss: 'Stop-loss below the Doji low.',
        confirmation: 'The third candle must close above the midpoint of the first candle. The Doji should have minimal body size.',
        candles: [
          { bodyTop: 35, bodyBottom: 70, wickTop: 30, wickBottom: 75, bullish: false },
          { bodyTop: 77, bodyBottom: 79, wickTop: 72, wickBottom: 85, bullish: true },
          { bodyTop: 28, bodyBottom: 60, wickTop: 24, wickBottom: 64, bullish: true },
        ],
        type: 'reversal',
      },
      {
        name: 'Evening Doji Star',
        sentiment: 'Strong Bearish',
        psychology: 'Like an Evening Star but the middle candle is a Doji — complete indecision at the top followed by heavy selling. The Doji pinpoints the exact exhaustion level.',
        entry: 'Enter short at the close of the third candle.',
        stopLoss: 'Stop-loss above the Doji high.',
        confirmation: 'The third candle must close below the midpoint of the first candle. Increasing volume on the third candle confirms the reversal.',
        candles: [
          { bodyTop: 40, bodyBottom: 75, wickTop: 35, wickBottom: 80, bullish: true },
          { bodyTop: 30, bodyBottom: 32, wickTop: 24, wickBottom: 38, bullish: false },
          { bodyTop: 42, bodyBottom: 78, wickTop: 38, wickBottom: 82, bullish: false },
        ],
        type: 'reversal',
      },
      {
        name: 'Rising Three Methods',
        sentiment: 'Strong Bullish',
        psychology: 'A long bullish candle, followed by 3 small bearish candles that stay within its range, then another long bullish candle that closes above the first. A brief rest within a strong uptrend — the trend continues.',
        entry: 'Enter long at the close of the fifth candle or on a break above the first candle high.',
        stopLoss: 'Stop-loss below the low of the small candles cluster.',
        confirmation: 'The fifth candle must close above the high of the first candle. The three middle candles should stay within the first candle range.',
        candles: [
          { bodyTop: 50, bodyBottom: 82, wickTop: 46, wickBottom: 86, bullish: true },
          { bodyTop: 55, bodyBottom: 62, wickTop: 52, wickBottom: 64, bullish: false },
          { bodyTop: 58, bodyBottom: 66, wickTop: 56, wickBottom: 68, bullish: false },
          { bodyTop: 62, bodyBottom: 70, wickTop: 60, wickBottom: 72, bullish: false },
          { bodyTop: 32, bodyBottom: 64, wickTop: 28, wickBottom: 66, bullish: true },
        ],
        type: 'continuation',
      },
      {
        name: 'Falling Three Methods',
        sentiment: 'Strong Bearish',
        psychology: 'A long bearish candle, followed by 3 small bullish candles that stay within its range, then another long bearish candle that closes below the first. A brief consolidation before sellers resume control.',
        entry: 'Enter short at the close of the fifth candle or on a break below the first candle low.',
        stopLoss: 'Stop-loss above the high of the small candles cluster.',
        confirmation: 'The fifth candle must close below the low of the first candle. The three middle candles should stay within the first candle range.',
        candles: [
          { bodyTop: 28, bodyBottom: 60, wickTop: 24, wickBottom: 64, bullish: false },
          { bodyTop: 48, bodyBottom: 55, wickTop: 46, wickBottom: 58, bullish: true },
          { bodyTop: 44, bodyBottom: 50, wickTop: 42, wickBottom: 52, bullish: true },
          { bodyTop: 40, bodyBottom: 46, wickTop: 38, wickBottom: 48, bullish: true },
          { bodyTop: 44, bodyBottom: 78, wickTop: 42, wickBottom: 82, bullish: false },
        ],
        type: 'continuation',
      },
    ],
  },
];
