export type IndicatorCategory = 'Trend' | 'Momentum' | 'Volatility' | 'Volume' | 'Fundamental';

export interface Indicator {
  name: string;
  shortName: string;
  category: IndicatorCategory;
  description: string;
  howToUse: string;
  whereToUse: string;
  benefits: [string, string, string];
  indianNote?: string;
}

export const indicators: Indicator[] = [
  // ── Trend ──
  {
    name: 'Simple Moving Average',
    shortName: 'SMA',
    category: 'Trend',
    description: 'The SMA calculates the average closing price over a set number of periods. It smooths out price noise to reveal the underlying trend direction.',
    howToUse: 'Plot SMA lines (e.g., 20 & 50 day) on the chart. A buy signal occurs when the shorter SMA crosses above the longer one (Golden Cross). A sell signal occurs on the opposite crossover (Death Cross).',
    whereToUse: 'Best used in trending markets. Avoid during choppy, sideways ranges where it generates frequent false signals.',
    benefits: ['Identifies trend direction at a glance', 'Generates clear crossover signals for entry/exit', 'Works across all timeframes — intraday to monthly'],
  },
  {
    name: 'Exponential Moving Average',
    shortName: 'EMA',
    category: 'Trend',
    description: 'The EMA gives more weight to recent prices, making it react faster than the SMA to price changes. It\'s preferred by short-term traders for quicker signals.',
    howToUse: 'Use 9 or 12-period EMA for short-term trades. Look for price bouncing off the EMA as dynamic support/resistance, or use EMA crossovers for entry signals.',
    whereToUse: 'Best for fast-moving or volatile markets where you need quicker trend detection than a standard SMA provides.',
    benefits: ['Reacts faster to price changes than SMA', 'Serves as dynamic support/resistance levels', 'Ideal for intraday and swing trading setups'],
  },
  {
    name: 'Moving Average Convergence Divergence',
    shortName: 'MACD',
    category: 'Trend',
    description: 'MACD measures the relationship between two EMAs (usually 12 & 26 period). The histogram shows momentum strength while the signal line provides trade triggers.',
    howToUse: 'Buy when the MACD line crosses above the signal line. Sell when it crosses below. Watch the histogram — growing bars mean strengthening momentum.',
    whereToUse: 'Best in trending markets. Extremely effective for confirming trend continuation or spotting early reversals.',
    benefits: ['Combines trend and momentum in one indicator', 'Histogram visually shows momentum strength', 'Divergences between MACD and price warn of reversals'],
  },
  {
    name: 'Average Directional Index',
    shortName: 'ADX',
    category: 'Trend',
    description: 'ADX measures trend strength on a 0-100 scale without indicating direction. Values above 25 signal a strong trend; below 20 suggests a range-bound market.',
    howToUse: 'Look for ADX rising above 25 to confirm a trend is worth trading. Use +DI and -DI crossovers for direction. ADX falling below 20 means switch to range strategies.',
    whereToUse: 'Use as a filter before entering trades — only take trend-following signals when ADX confirms a strong trend.',
    benefits: ['Quantifies trend strength objectively', 'Filters out weak, choppy market conditions', 'Helps choose between trend and range strategies'],
  },
  {
    name: 'Ichimoku Cloud',
    shortName: 'Ichimoku',
    category: 'Trend',
    description: 'Ichimoku Kinko Hyo is an all-in-one indicator showing support, resistance, trend direction, and momentum via five lines and a shaded cloud.',
    howToUse: 'Price above the cloud is bullish, below is bearish. A Tenkan-Kijun cross inside the cloud is a strong signal. Cloud thickness indicates support/resistance strength.',
    whereToUse: 'Best in trending markets with strong directional moves. Popular on daily and weekly charts for swing and position trading.',
    benefits: ['Provides a complete market picture in one glance', 'Cloud acts as dynamic support and resistance zones', 'Forward-projected cloud helps anticipate future levels'],
  },
  {
    name: 'Parabolic SAR',
    shortName: 'PSAR',
    category: 'Trend',
    description: 'Parabolic SAR places dots above or below the price to indicate trend direction. When dots flip from below to above price, it signals a potential sell.',
    howToUse: 'Enter long when dots appear below the candles, short when above. Use the dots as trailing stop-loss levels. Flip your position when dots switch sides.',
    whereToUse: 'Works best in trending markets with clear directional moves. Avoid in consolidation zones where it whipsaws frequently.',
    benefits: ['Provides clear visual stop-loss levels', 'Automatically tightens trailing stops as trends mature', 'Simple dot-based signals for beginners'],
  },
  {
    name: 'Supertrend',
    shortName: 'Supertrend',
    category: 'Trend',
    description: 'Supertrend uses ATR and a multiplier to plot a single line that flips color between bullish (green) and bearish (red). Very popular among Indian traders.',
    howToUse: 'Buy when the Supertrend line turns green (below price). Sell when it turns red (above price). Use a multiplier of 3 and period of 10 for balanced signals.',
    whereToUse: 'Excellent in trending Nifty/Sensex moves. Widely used by Indian intraday traders for clean entry and exit signals.',
    benefits: ['Extremely simple buy/sell color-coded signals', 'Works well as a trailing stop mechanism', 'Very popular and widely tested on Indian markets'],
  },

  // ── Momentum ──
  {
    name: 'Relative Strength Index',
    shortName: 'RSI',
    category: 'Momentum',
    description: 'RSI oscillates between 0-100 and measures the speed of price movements. Values above 70 indicate overbought conditions, below 30 indicate oversold.',
    howToUse: 'Look for the line crossing above 30 for buy signals (oversold bounce) and crossing below 70 for sell signals (overbought reversal). Divergences are powerful setups.',
    whereToUse: 'Best in range-bound markets for mean-reversion trades. In strong trends, RSI can stay overbought/oversold for extended periods.',
    benefits: ['Identifies overbought and oversold conditions', 'RSI divergence is one of the most reliable reversal signals', 'Works across all asset classes and timeframes'],
  },
  {
    name: 'Stochastic Oscillator',
    shortName: 'Stochastic',
    category: 'Momentum',
    description: 'Stochastic compares a stock\'s closing price to its price range over a period. The %K and %D lines oscillate 0-100, with 80+ overbought and 20- oversold.',
    howToUse: 'Buy when %K crosses above %D below the 20 level. Sell when %K crosses below %D above the 80 level. Use the 14-period setting for standard signals.',
    whereToUse: 'Best during sideways or ranging markets. Combine with trend indicators to filter signals in the direction of the larger trend.',
    benefits: ['Provides early momentum shift signals', 'Dual-line crossovers confirm trade entries', 'Effective for timing entries within established trends'],
  },
  {
    name: 'Williams %R',
    shortName: 'Williams %R',
    category: 'Momentum',
    description: 'Williams %R is an inverted oscillator ranging from 0 to -100. Readings above -20 are overbought, below -80 are oversold. It\'s faster than RSI.',
    howToUse: 'Look for %R to move from below -80 back above it for buy signals. Sell when %R drops from above -20. The speed makes it useful for short-term momentum.',
    whereToUse: 'Use during ranging and mildly trending markets. Combine with a trend filter to avoid false signals in strong trends.',
    benefits: ['Reacts faster than RSI to price changes', 'Clean overbought/oversold boundaries', 'Great for short-term swing trade timing'],
  },
  {
    name: 'Rate of Change',
    shortName: 'ROC',
    category: 'Momentum',
    description: 'ROC measures the percentage change in price between the current price and the price N periods ago. It oscillates around zero, showing momentum direction.',
    howToUse: 'ROC crossing above zero signals bullish momentum. Crossing below zero signals bearish momentum. Extreme readings indicate potential reversals.',
    whereToUse: 'Useful in all market conditions. High ROC in trending markets confirms strength; diverging ROC warns of weakening momentum.',
    benefits: ['Measures pure momentum as a percentage', 'Zero-line crossovers provide clean signals', 'Divergences reliably warn of trend exhaustion'],
  },
  {
    name: 'Commodity Channel Index',
    shortName: 'CCI',
    category: 'Momentum',
    description: 'CCI measures how far the current price deviates from its statistical average. Readings above +100 are overbought, below -100 are oversold.',
    howToUse: 'Enter long when CCI rises above -100 from below (oversold recovery). Enter short when CCI drops below +100 from above. Extreme values signal potential reversals.',
    whereToUse: 'Works in both trending and ranging markets. Particularly useful for cyclical stocks that oscillate between extremes.',
    benefits: ['Identifies cyclical highs and lows effectively', 'Unbounded scale captures extreme momentum moves', 'Works well for commodities and cyclical sectors'],
  },

  // ── Volatility ──
  {
    name: 'Bollinger Bands',
    shortName: 'BB',
    category: 'Volatility',
    description: 'Bollinger Bands plot an upper and lower band 2 standard deviations from a 20-period SMA. Price touching the bands signals potential reversals or breakouts.',
    howToUse: 'Buy near the lower band in an uptrend (mean reversion). A "squeeze" (bands contracting) warns of an upcoming explosive move. Breakout above the upper band with volume confirms momentum.',
    whereToUse: 'Versatile in all markets. Use for mean-reversion in ranges and breakout detection during consolidation periods.',
    benefits: ['Adapts dynamically to market volatility', 'Band squeezes predict explosive breakout moves', 'Upper/lower bands act as dynamic overbought/oversold levels'],
  },
  {
    name: 'Average True Range',
    shortName: 'ATR',
    category: 'Volatility',
    description: 'ATR measures market volatility by calculating the average range between high and low prices. Higher ATR means more volatility. It does not indicate direction.',
    howToUse: 'Use ATR to set stop-loss distances — a common approach is 2× ATR below your entry. Rising ATR during a trend confirms conviction; falling ATR suggests the move is losing steam.',
    whereToUse: 'Essential for position sizing and stop-loss placement in any market condition. Always use alongside directional indicators.',
    benefits: ['Quantifies volatility for smarter position sizing', 'Prevents setting stops too tight or too wide', 'Identifies when markets are becoming more or less active'],
  },
  {
    name: 'Standard Deviation',
    shortName: 'StdDev',
    category: 'Volatility',
    description: 'Standard Deviation measures how dispersed prices are from their average. Higher values indicate increased volatility, lower values suggest calm markets.',
    howToUse: 'Watch for rising standard deviation to anticipate trending moves. Falling standard deviation often precedes breakouts from consolidation. Use as a filter for other indicators.',
    whereToUse: 'Use to gauge overall market volatility regime. Combine with other indicators to adjust strategy between trending and ranging conditions.',
    benefits: ['Foundation for many other indicators like Bollinger Bands', 'Helps quantify risk and expected price range', 'Identifies volatility cycles for strategic planning'],
  },

  // ── Volume ──
  {
    name: 'On-Balance Volume',
    shortName: 'OBV',
    category: 'Volume',
    description: 'OBV adds volume on up days and subtracts it on down days. A rising OBV confirms bullish pressure; divergence between OBV and price signals a potential reversal.',
    howToUse: 'If price makes a new high but OBV doesn\'t, it\'s a bearish divergence. Rising OBV with rising price confirms the trend. Use OBV breakouts to anticipate price breakouts.',
    whereToUse: 'Effective in all market conditions. Particularly powerful for confirming breakouts and detecting institutional accumulation/distribution.',
    benefits: ['Reveals whether volume supports the price trend', 'OBV divergence is an early reversal warning', 'Detects smart money accumulation before price moves'],
  },
  {
    name: 'Volume Weighted Average Price',
    shortName: 'VWAP',
    category: 'Volume',
    description: 'VWAP calculates the average price weighted by volume for the trading day. Institutional traders use it as a benchmark for fair value during the session.',
    howToUse: 'Buy when price pulls back to VWAP from above in an uptrend. Sell when price rallies to VWAP from below in a downtrend. Price above VWAP = bullish bias, below = bearish.',
    whereToUse: 'Primarily an intraday indicator. Essential for institutional-quality execution and day trading strategies.',
    benefits: ['Shows the true average price institutions paid', 'Acts as dynamic intraday support/resistance', 'Standard benchmark for day trading execution quality'],
  },
  {
    name: 'Money Flow Index',
    shortName: 'MFI',
    category: 'Volume',
    description: 'MFI is the volume-weighted version of RSI, oscillating 0-100. It measures buying and selling pressure using both price and volume data.',
    howToUse: 'MFI above 80 is overbought (potential sell), below 20 is oversold (potential buy). MFI divergence from price is a stronger signal than RSI divergence because it includes volume.',
    whereToUse: 'Use in range-bound markets for mean-reversion setups. MFI divergences are particularly reliable during sideways consolidation phases.',
    benefits: ['Incorporates volume for more reliable signals than RSI', 'Overbought/oversold levels backed by actual money flow', 'Divergences detect institutional activity shifts'],
  },
  {
    name: 'Chaikin Money Flow',
    shortName: 'CMF',
    category: 'Volume',
    description: 'CMF measures accumulation/distribution over a period (usually 20 days). Positive CMF means buying pressure; negative means selling pressure.',
    howToUse: 'CMF above 0 confirms bullish accumulation — stay long. CMF below 0 confirms distribution — stay short or exit longs. Rising CMF with rising price is a strong bullish confirmation.',
    whereToUse: 'Best used to confirm trends and breakouts. A breakout with positive CMF is more likely to succeed than one with negative CMF.',
    benefits: ['Confirms whether money is flowing into or out of a stock', 'Helps validate breakout authenticity', 'Simple above/below zero reading is easy to interpret'],
  },
  {
    name: 'Accumulation/Distribution',
    shortName: 'A/D',
    category: 'Volume',
    description: 'The A/D line uses volume and the close\'s position within the day\'s range to measure cumulative money flow. Rising A/D confirms buying; falling confirms selling.',
    howToUse: 'Compare A/D direction with price direction. If price rises but A/D falls, smart money may be distributing — be cautious. A/D rising before price often predicts breakouts.',
    whereToUse: 'Use alongside price trends for confirmation. Especially useful for detecting divergences that precede major reversals in large-cap stocks.',
    benefits: ['Tracks institutional accumulation and distribution', 'Leading indicator — often moves before price', 'Divergences reveal hidden buying/selling pressure'],
  },

  // ── Fundamental ──
  {
    name: 'Earnings Per Share',
    shortName: 'EPS',
    category: 'Fundamental',
    description: 'EPS shows how much profit a company earns for each outstanding share. Higher EPS generally means a more profitable company. Calculated as Net Income ÷ Shares Outstanding.',
    howToUse: 'Compare EPS growth quarter-over-quarter and year-over-year. Rising EPS indicates improving profitability. Use alongside P/E to determine if a stock is fairly priced.',
    whereToUse: 'Essential for fundamental analysis during earnings season. Use for long-term investment decisions and comparing companies within the same sector.',
    benefits: ['Direct measure of a company\'s profitability per share', 'EPS growth drives long-term stock price appreciation', 'Basis for calculating the P/E ratio and fair value'],
  },
  {
    name: 'Price-to-Earnings Ratio',
    shortName: 'P/E Ratio',
    category: 'Fundamental',
    description: 'P/E Ratio measures how much investors pay for each rupee of earnings. A high P/E means high growth expectations; a low P/E may indicate undervaluation.',
    howToUse: 'Compare a stock\'s P/E to its industry average and historical P/E. P/E below the sector average may signal a buying opportunity. Very high P/E warrants caution unless growth justifies it.',
    whereToUse: 'Use for valuing stocks before long-term investments. Most useful when comparing companies in the same sector on Nifty/Sensex.',
    benefits: ['Most widely used valuation metric globally', 'Quick comparison tool across industry peers', 'Helps identify overvalued and undervalued stocks'],
  },
  {
    name: 'Price-to-Book Ratio',
    shortName: 'P/B Ratio',
    category: 'Fundamental',
    description: 'P/B compares market price to book value (assets minus liabilities). A P/B below 1 could mean the stock is undervalued or the business has fundamental problems.',
    howToUse: 'Look for P/B below industry average for potential value picks. For banks and financials, P/B is the primary valuation metric. Always check why P/B is low before buying.',
    whereToUse: 'Critical for banking and financial sector analysis. Also useful for asset-heavy industries like manufacturing and real estate.',
    benefits: ['Key valuation metric for banks and NBFCs', 'Identifies potential value opportunities', 'Useful floor for valuation when earnings are negative'],
  },
  {
    name: 'PEG Ratio',
    shortName: 'PEG',
    category: 'Fundamental',
    description: 'PEG adjusts the P/E ratio by the company\'s earnings growth rate. A PEG below 1 suggests the stock is undervalued relative to its growth; above 1 may be overvalued.',
    howToUse: 'Calculate PEG as P/E ÷ EPS Growth Rate. PEG < 1 is a potential buy signal for growth stocks. Compare PEG ratios within the same sector for the best growth-at-reasonable-price picks.',
    whereToUse: 'Best for evaluating growth stocks where a high P/E alone might be misleading. Essential for comparing IT and pharma stocks on Indian markets.',
    benefits: ['Adds growth context that raw P/E misses', 'Identifies the best growth-at-reasonable-price opportunities', 'Simple rule — PEG under 1 signals potential undervaluation'],
  },
  {
    name: 'Return on Equity',
    shortName: 'ROE',
    category: 'Fundamental',
    description: 'ROE measures how efficiently a company generates profit from shareholder equity. Calculated as Net Income ÷ Shareholder Equity. Higher ROE indicates better management.',
    howToUse: 'Look for ROE consistently above 15% — this indicates strong management efficiency. Compare ROE across years to check for improving or declining performance.',
    whereToUse: 'Use for evaluating management quality in long-term investments. Essential when comparing companies within the same industry.',
    benefits: ['Measures management efficiency with shareholder capital', 'Consistently high ROE signals a competitive moat', 'Helps filter quality stocks for long-term portfolios'],
  },
  {
    name: 'Return on Capital Employed',
    shortName: 'ROCE',
    category: 'Fundamental',
    description: 'ROCE measures profit generated from all capital (debt + equity). It\'s broader than ROE and shows how well a company uses all its capital to generate returns.',
    howToUse: 'ROCE above 20% is excellent. Compare to the company\'s cost of capital — ROCE must be higher for value creation. Rising ROCE over years signals improving capital efficiency.',
    whereToUse: 'Use for capital-intensive industries like manufacturing, infrastructure, and telecom where debt levels significantly impact returns.',
    benefits: ['Accounts for both debt and equity capital', 'Better than ROE for capital-intensive businesses', 'Rising ROCE indicates improving business economics'],
  },
  {
    name: 'Debt-to-Equity Ratio',
    shortName: 'D/E',
    category: 'Fundamental',
    description: 'D/E compares total debt to shareholder equity. A lower ratio means less financial risk. A D/E above 2 is generally considered highly leveraged.',
    howToUse: 'Prefer D/E below 1 for conservative investments. For banking/NBFCs, higher D/E is normal. Compare D/E within the same industry — never across different sectors.',
    whereToUse: 'Critical for assessing financial risk before long-term investment. Especially important during rising interest rate environments in India.',
    benefits: ['Quick assessment of financial leverage and risk', 'Identifies companies vulnerable to interest rate hikes', 'Essential safety check before committing capital'],
  },
  {
    name: 'Dividend Yield',
    shortName: 'Div Yield',
    category: 'Fundamental',
    description: 'Dividend Yield shows annual dividends as a percentage of stock price. Higher yield provides regular income but very high yields may signal unsustainable payouts.',
    howToUse: 'Look for yields between 2-5% with consistent payment history. Check the payout ratio — if it exceeds 80% of earnings, the dividend may not be sustainable.',
    whereToUse: 'Use for building income-generating portfolios. Popular PSU stocks on NSE often offer attractive dividend yields.',
    benefits: ['Provides regular passive income from investments', 'High-yield stocks often outperform during market downturns', 'Dividend consistency indicates financial stability'],
  },
  {
    name: 'Quick Ratio',
    shortName: 'Quick Ratio',
    category: 'Fundamental',
    description: 'Quick Ratio (Acid Test) measures a company\'s ability to pay short-term obligations using liquid assets (cash + receivables). A ratio above 1 is healthy.',
    howToUse: 'Quick Ratio above 1 means the company can cover immediate liabilities. Below 0.5 is a red flag. Compare over quarters to detect deteriorating liquidity.',
    whereToUse: 'Essential for assessing financial health, especially for small and mid-cap stocks. Critical during economic downturns or tight credit conditions.',
    benefits: ['Measures immediate liquidity health', 'Catches cash-flow problems before they become crises', 'More conservative and reliable than the Current Ratio'],
  },
  {
    name: 'Free Cash Flow',
    shortName: 'FCF',
    category: 'Fundamental',
    description: 'FCF is the cash remaining after capital expenditures. Positive FCF means the company can fund growth, pay dividends, and reduce debt without external financing.',
    howToUse: 'Look for consistently positive and growing FCF. Compare FCF to net income — if net income is high but FCF is low, earnings quality may be poor.',
    whereToUse: 'Use for evaluating long-term investment candidates. Particularly important for growth companies claiming profitability — FCF tells the real story.',
    benefits: ['Shows actual cash generation, not just accounting profit', 'Growing FCF is the strongest sign of business health', 'Funds buybacks, dividends, and expansion without debt'],
  },
];

export const categoryIcons: Record<IndicatorCategory, string> = {
  Trend: 'TrendingUp',
  Momentum: 'Zap',
  Volatility: 'Activity',
  Volume: 'BarChart3',
  Fundamental: 'Building2',
};

export const categoryColors: Record<IndicatorCategory, string> = {
  Trend: 'bg-terminal-cyan/20 text-terminal-cyan border-terminal-cyan/30',
  Momentum: 'bg-terminal-gold/20 text-terminal-gold border-terminal-gold/30',
  Volatility: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  Volume: 'bg-terminal-green/20 text-terminal-green border-terminal-green/30',
  Fundamental: 'bg-orange-500/20 text-orange-400 border-orange-500/30',
};
