project_id = "cnrkynvgwaoqfayuceci"

[functions.stock-news]
verify_jwt = false

[functions.stock-analysis]
verify_jwt = false

[functions.stock-price]
verify_jwt = false

[functions.pattern-explain]
verify_jwt = false
